BitLayer/Models/ErrorViewModel.cs
namespace BitLayer.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BitLayer/Models/UserLogindto.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BitLayer.Models
{
    public class UserLogindto
    {
        [EmailAddress, Required]
        public string Email { get; set; }

        [PasswordPropertyText, Required]
        public string Password { get; set; }

    }
}

BitLayer/Models/UserRegisterDto.cs
using System.ComponentModel.DataAnnotations;

namespace BitLayer.Models
{
    public class UserRegisterDto
    {
        [Required]
        public string Name { get; set; }

        [Required , EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Password { get; set; }

        [Required]
        public string confirmPassword { get; set; }

        public string Image { get; set; }




        public IFormFile UploadImage { get; set; }
    }
}

BitLayer/Controllers/DepartmentController.cs
using Bitlayer.Bll.Services;
using BitLayer.Domain.Models;
using dataTable.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace BitLayer.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _department;

        public DepartmentController(IDepartmentService department)
        {
            _department = department;
        }


        public IActionResult Index()
        {
            return View();   
        }

        [HttpPost]
        public JsonResult GetAllDepartment()
        {

            var request = new DataTableRequest();

            request.Draw = Convert.ToInt32(Request.Form["draw"].FirstOrDefault());
            request.Start = Convert.ToInt32(Request.Form["start"].FirstOrDefault());
            request.Length = Convert.ToInt32(Request.Form["length"].FirstOrDefault());
            request.Search = new DataTableSearch()
            {
                Value = Request.Form["search[value]"].FirstOrDefault()
            };
            request.Order = new DataTableOrder[] {
            new DataTableOrder()
            {
                Dir = Request.Form["order[0][dir]"].FirstOrDefault(),
                Column = Convert.ToInt32(Request.Form["order[0][column]"].FirstOrDefault())
            }};

            return Json(_department.GetDepartmentAsync(request).Result);

        }




        [HttpPost]
        public IActionResult Add(Department department)
        {
           
                _department.AddDepartment(department);

            return View();



        }

        [HttpPost]
        public IActionResult Edit(int Id,Department department)
        {

            _department.EditDepartment(Id ,department);
            return Json(new { success = true, message = "Update Successfully" });



        }


        [HttpPost]
        public IActionResult detail(int Id)
        {

            var dep =  _department.GetDepartmentById(Id);
            return View(dep);



        }

        [HttpPost]
        public IActionResult Delete(int Id)
        {

            _department.DeleteDep(Id);
            return Json(new { success = true, message = "Delete Successfully" });



        }
    }
}

BitLayer/Controllers/HomeController.cs
using BitLayer.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BitLayer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BitLayer/Controllers/UserController.cs
using Bitlayer.Bll.Services;
using BitLayer.Domain.Models;
using BitLayer.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.VisualBasic;
using System.Security.Cryptography;

namespace BitLayer.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserServices _user;

        public UserController(IUserServices user)
        {
            _user = user;
        }


        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Register() => View();


        [HttpPost]
        public IActionResult Register(UserRegisterDto dto)
        {

            _user.CreatePasswordHash(dto.Password, out byte[] passwordHash, out byte[] passwordSalt);

            var password = passwordSalt + "::" + passwordHash;




            if (dto.Password == dto.confirmPassword)
            {
                var user = new User
                {
                    Name = dto.Name,
                    Email = dto.Email,
                    Password = password,
                    Image = dto.Image,

                };





               _user.Register(user);

                return RedirectToAction("Login");
            }

            else
            {
                return BadRequest("password dosn't match!");


            }

        }


        public IActionResult Login() => View();

        [HttpPost]
        public IActionResult Login(UserLogindto dto)
        {

            var user = new User();

            


            var res = _user.Login(dto.Email);

                

            _user.CreatePasswordHash(dto.Password, out byte[] passwordHash, out byte[] passwordSalt);

            var password = passwordSalt + "::" + passwordHash;


            if (password != res.Password)
            {
                return BadRequest("password dos't match");


            }



            return RedirectToRoute("Default");
            

           

            
             
            }

        }



    }
    

BitLayer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

BitLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BitLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BitLayer.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css" rel="stylesheet" />

 </head>
<body>




    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BitLayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BitLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/department.js"></script>
  

   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BitLayer/Views/User/Login.cshtml
@model BitLayer.Models.UserLogindto
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<form method="post">


<div class="form-group">
    <label asp-for="Email"></label>
    <input asp-for="Email" class="form-control" type="email" />
    <label id="Email-error" class="error" for="Email" style="display:none"></label>
</div>

<div class="form-group">
    <label asp-for="Password"></label>
    <input asp-for="Password" class="form-control" type="password" />
    <label id="Password-error" class="error" for="Password" style="display:none"></label>
</div>
    <button type="submit" class="btn-primary">Register</button>

</form>

BitLayer/Views/User/Register.cshtml
@model BitLayer.Models.UserRegisterDto
@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>



<form method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <label id="Email-error" class="error" for="Email" style="display:none"></label>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" type="email" />
        <label id="Email-error" class="error" for="Email" style="display:none"></label>
    </div>

    <div class="form-group">
        <label asp-for="Password"></label>
        <input asp-for="Password" class="form-control" type="password" />
        <label id="Password-error" class="error" for="Password" style="display:none"></label>
    </div>
    <div class="form-group">
        <label asp-for="confirmPassword"></label>
        <input asp-for="confirmPassword" class="form-control" type="password" />
        <label id="ConfirmPassword-error" class="error" for="ConfirmPassword" style="display:none"></label>
    </div>


    <button type="submit" class="btn-primary">Register</button>

</form>